# Chapter 2: Coding Our First Neurons

We firstly use pure-Python method, then we will use NumPy and Matplotlib for some visualizations.

## 2.1. A Single Neuron

<center><img src='./image/2-1.png' style='width: 60%'/></center>


In [1]:
# There are three inputs to a single neuron.
inputs = [1 ,2 , 3]

# Each input needs a weight associated with it. In most case, weights are initialized randomly.
weights = [0.2, 0.8, - 0.5]

# Each neuron has a bias associated with it. In most case, biases set as zero to start.
bias = 2

# The values for weights and biases are what get “trained” and they are what make a model work (or not work).
output = (inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias)
print(output)

2.3


If we have four inputs for a single neuron:

<center><img src='./image/2-2.png' style='width: 60%'/></center>

In [2]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, - 0.5, 1.0]
bias = 2.0
output = (inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] 
+ inputs[3] * weights[3] + bias)
print(output)

4.8



## 2.2. A Layer of Neurons

A layer of neurons has more than one neuron.

An example network with 04 inputs and 3 neurons:

<center><img src='./image/2-3.png' style='width: 60%'/></center>

There are three sets of weights and three biases, which define three neurons.

In a fully connected NN, every neuron in the current layer has connections to every neuron from the previous layer.

In [3]:
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5
outputs = [
    # Neuron 1:
    inputs[0] * weights1[0] + inputs[1] * weights1[1] +
    inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1,
    # Neuron 2:
    inputs[0] * weights2[0] + inputs[1] * weights2[1] +
    inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2,
    # Neuron 3:
    inputs[0] * weights3[0] + inputs[1] * weights3[1] +
    inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3]
print(outputs)


[4.8, 1.21, 2.385]


In a deep NN with many more layers and neurons, it is very challenging to hardcode using the current methods. Instead, we use a loop to scale and handle dynamically sized inputs and layers.

Python alone doesn’t do matrix/tensor/array math very efficiently.

The most popular deep learning library in Python is “TensorFlow” that do all operations on tensors.

In [4]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# Output of current layer
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip (weights, biases):
    
    # Zeroed output of given neuron
    neuron_output = 0
    
    # For each input and weight to the neuron
    for n_input, weight in zip (inputs, neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron’s output variable
        neuron_output += n_input * weight
    
    # Add bias
    neuron_output += neuron_bias
    
    # Put neuron’s result to the layer’s output list
    layer_outputs.append(neuron_output)

print(layer_outputs)


[4.8, 1.21, 2.385]


## 2.3. Tensors, Arrays and Vectors

### 2.3.1. What are “tensors”?

Tensors are closely related to arrays.

To understand a tensor, let’s compare and describe some of the other data containers in Python.

#### A Python list

A Python list is a comma-separated object contained in brackets.

    A = [1, 3, 4, 6]            is a list.
    
    B = [[1, 2, 3, 5],
        [5, 8, 9, 3]]           is a list of lists.
    
    C = [[[ 1 , 5 , 6 , 2 ],
          [ 3 , 2 , 1 , 3 ]],
         [[ 5 , 2 , 1 , 2 ],
          [ 6 , 4 , 8 , 4 ]],
         [[ 2 , 8 , 5 , 3 ],
          [ 1 , 1 , 9 , 4 ]]]	is a list of lists of lists.

A, B, C could be an array or an array representation of a tensor, as they are homologous.

The following D list cannot be an array as it is not homologous.

    D = [[ 4 , 2 , 3 ],
        [ 5 , 1 ]]

Every dimension of a list should be the same length to make it become an array.

#### A matrix

A matrix is simple, it is a rectangular array. It has columns and rows.

Can all arrays be matrices?

- No, an array can be far more than just columns and rows.
- It could have 4D, 20D, …

E could also be a matrix, which automatically means it could also be an array.

    E = [[4, 2], [5, 1], [8, 2]]

F is a 3D array with 3 levels of brackets.

    F = [[[ 1 , 5 , 6 , 2 ], [ 3 , 2 , 1 , 3 ]],
        [[ 5 , 2 , 1 , 2 ], [ 6 , 4 , 8 , 4 ]],
        [[ 2 , 8 , 5 , 3 ], [ 1 , 1 , 9 , 4 ]]]

    shape(F) = (3, 2, 4)

#### A tensor

What is a tensor, to a computer scientist, in the context of deep learning?
- A tensor object is an object that can be represented as an array.
- An array is an ordered homologous container for numbers (i.e., NumPy)
- A linear array (1D array) is the simplest example of an array, and in plain Python, it would be a list. It is also a vector in math.
- 2D array represent a matrix in mathematics.
- Each element of the array can be accessed using a tuple of indices as a key.


## 2.4. Dot Product and Vector Addition

1D array is just a vector (or a list in Python).

A dot product of two vectors is a scalar.

$$
\vec{a} \cdot \vec{b} = \sum_{i=1}^{n} a_i b_i = a_1 b_1 + a_2 b_2 + \cdots + a_n b_n
$$

In [5]:
a = [1, 2, 3]
b = [2, 3, 4] 
dot_product = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
print(dot_product)

20


What if we call $a$ “inputs” and $b$ “weights”?

Plain Python doesn’t contain methods or functions to perform such an operation, so we need $\textbf{NumPy}$.

Numpy lets us to perform a vector addition operation in a natural way.

$$
\vec{a} + \vec{b} = \Big[ a_1 + b_1 ,  a_2 + b_2 , \cdots ,  a_n + b_n\Big]
$$

The two vectors should have the same size and result is a vector of the same size.


## 2.5. Single Neuron with NumPy

Numpy makes the code simpler to read and write, and faster to run:

In [6]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias

print (outputs)

4.8


## 2.6. A Layer of Neurons with NumPy

A layer of 3 neurons is used, the weights will be a matrix or list of weight vectors.

We need to perform the dot product of the weight matrix and the input vector
.
The matrix is considered as a list of vectors, and the dot product is performed one by one with the vector of inputs, returning a list of dot products.


In [7]:
import numpy as np
inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
weights = [[ 0.2 , 0.8 , - 0.5 , 1 ], [0.5 , - 0.91 , 0.26 , - 0.5 ], [- 0.26 , - 0.27 , 0.17 , 0.87 ]]
biases = [ 2.0 , 3.0 , 0.5 ]
layer_outputs = np.dot(weights, inputs) + biases	# for the plain Python list addition, NumPy will convert it to an array internally
print(layer_outputs)

[4.8   1.21  2.385]


## 2.7. A Batch of Data

NNs receive data in batches.

A feature set (an observation or a sample) contains of various features.

    inputs =[1 ,2 ,3 , 25]

NNs expect to take in many samples at a time for 2 reasons.

- It’s faster to train in batches in parallel processing

- Batches help with generalization during training, training or fitting in batches gives you a higher chance of making more meaningful changes to weights and biases

<center><img src='./image/2-4.png' style='width: 60%'/></center>

An example of a batch of observations:

    inputs = [[1, 2, 3, 2.5], [2, 5, -1, 2], [-1.5, 2.7, 3.3, -0.8]]
   
Each list in this larger list is a sample representing a feature set.

Now, we have matrix of inputs and a matrix of weights. We need to manage both matrices as lists of vectors and perform dot products on all of them in all combinations, resulting in a list of lists of outputs, or a matrix, this operation is the matrix product.

## 2.8. Matrix Product

In a matrix product, the size of the second dimension of the left matrix must match the size of the first dimension of the right matrix.

Row and column vectors are matrices with one of their dimensions being of a size of 1.

$$
a = \begin{bmatrix}
1 & 2 & 3 
\end{bmatrix}\,\,\,\,\,
b = \begin{bmatrix}
2 \\
3 \\
4
\end{bmatrix}
$$

$$
ab = 
\begin{bmatrix}
1 & 2 & 3 
\end{bmatrix} 
\begin{bmatrix}
2 \\
3 \\
4
\end{bmatrix} 
= \big[ 20 \big]
$$

## 2.9. Transposition of the Matrix Product

A dot product of two vectors equals a matrix product of a row and column vector.

$$
\vec{a} \cdot \vec{b} = ab^T = 
\begin{bmatrix}
1 & 2 & 3 
\end{bmatrix} 
\begin{bmatrix}
2 \\
3 \\
4
\end{bmatrix} 
= \big[ 20 \big]
$$

Transposition modifies a matrix in a way that its rows become columns and columns become rows.

<center><img src='./image/2-5.png' style='width: 60%'/></center>

<center><img src='./image/2-6.png' style='width: 60%'/></center>

A row vector is a matrix with size $(1,n)$. It is a $1 \times n$ array of array of shape $(1,n)$.

$$
a= \begin{bmatrix}
a_1 & a_2 & a_3 & \cdots & a_n 
\end{bmatrix}
$$

In [8]:
np.array([[ 1 , 2 , 3 ]])

# To transform a list into a matrix containing a single row, put it in to a list and create numpy array
a = [1, 2, 3]
np.array([a])

# Or we can turn it into a 1D array and expand dimensions using one of the NumPy abilities.
a = [1, 2, 3]
np.expand_dims(np.array(a), axis = 0)    # add a new dimension at the index of the axis

a = [ 1 , 2 , 3 ]
b = [ 2 , 3 , 4 ]
a = np.array([a])
b = np.array([b]).T
np.dot(a, b)


array([[20]])

We achieved the same result as the dot product of two vectors, but performed on matrices and returning a matrix.

NumPy does not have a dedicated method for performing matrix product – the dot product and matrix product are both implemented in a single method: `np.dot()`

## 2.10. A Layer of Neurons & Batch of Data w/ NumPy

In NNs, we need to perform the matrix product between input and weight matrices.

We need to transform the second arguments (weights) to turn the row vectors into column vectors.

- When the inputs are a vector, we can perform the dot product on the inputs and the weights without a transposition.
- When the inputs aee a batch of inputs (a matrix), need to perform matrix product. It takes all of the combinations of rows from the left matrix and columns from the right matrix, performing dot product of them and placing the results in an output array.
- Both arrays have the same shape, but to perform the matrix product, the shape’s value from the index 1 of the first matrix and the index 0 of the second matrix must match.

The following don’t match.

<center><img src='./image/2-7.png' style='width: 40%'/></center>

We should transpose the second array.

<center><img src='./image/2-8.png' style='width: 40%'/></center>

We can `np.dot()` on a plain Python list of lists as NumPy will convert them to matrices internally.

Plain Python list of lists does not support the transposition operation, `.T`, we need NumPy.

The addition of biases don’t need to convert them to matrices, as NumPy do it internally.

- Each column of the matrix product result is an output of one neuron.
- The bias vector is added to each row vector – the bias of each neuron needs to be added to all of the results of this neuron performed on all input vectors (samples).

Our NN takes in a group of samples (inputs) and outputs a group of predictions.

In [9]:
import numpy as np
inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]
layer_outputs = np.dot(inputs, np.array(weights).T) + biases
print (layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
